import "./globals.scss";
import "./bootstrap.scss";
import NavBar from "./NavBar";
import Footer from "./Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang="zh-Hans-CN">
      <body>
        <NavBar />
        <div className="container-lg" style={{ marginTop: "2rem" }}>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
