import "./globals.scss";
import "./bootstrap.scss";
import { Inter } from "next/font/google";
import getCounterData from "@/lib/counter";
import Counter from "@/components/Counter";
import NavBar from "./NavBar";
import Footer from "./Footer";

export const dynamic = "force-dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh-Hans-CN">
      <body>
        <NavBar />
        <div
          className={`container-lg ${inter.className}`}
          style={{ marginTop: "2rem" }}
        >
          {children}
        </div>
        <Footer>
          <Counter
            fallbackData={await getCounterData()}
            refreshInterval={10000}
          />
        </Footer>
      </body>
    </html>
  );
}
