import "./bootstrap.scss";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh-Hans-CN">
      <body>
        <NavBar />
        <div
          className={`container-lg ${inter.className}`}
          style={{ marginTop: "6rem" }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
